import { DarkTheme, DefaultTheme, ThemeProvider } from '@react-navigation/native';
import { onValue, ref, update } from 'firebase/database';
import React, { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';
import { useColorScheme as useRNColorScheme } from 'react-native';
import { db } from '../../firebaseConfig';

export type ThemeMode = 'light' | 'dark';
export type Language = 'vi' | 'en';

type AppSettingsContextType = {
  theme: ThemeMode;
  language: Language;
  setTheme: (mode: ThemeMode) => void;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  vi: {
    'common.success': 'Thành công',
    'common.error': 'Lỗi',
    'common.cancel': 'Hủy',
    'nav.overview': 'Tổng quan',
    'nav.graph': 'Thống kê',
    'nav.news': 'Tin tức',
    'nav.notifications': 'Thông báo',
    'nav.profile': 'Hồ sơ',
    'home.active': 'Điều khiển thiết bị',
    'home.sensors': 'Thông số nhiệt độ và độ ẩm bãi xe',
    'home.settings': '⚙️ Thiết lập hệ thống',
    'home.title': 'Chủ động',
    'home.overview': 'Tổng quan',
    'home.graph': 'Thống kê',
    'home.temp': 'Nhiệt độ',
    'home.humi': 'Độ ẩm',
    'home.unitTemp': '°C',
    'home.unitHumi': '%',
    'home.light': 'Đèn',
    'home.alarm': 'Chuông báo',
    'home.door': 'Cửa ra/vào',
    'home.parking': 'Bãi đậu',
    'home.on': 'BẬT',
    'home.off': 'TẮT',
    'home.access': 'Truy cập',
    'home.check': 'Kiểm tra',
    'home.done': 'Hoàn thành',
    'home.tempTitle': 'Ngưỡng Nhiệt',
    'home.timeOnTitle': 'Giờ mở đèn',
    'home.timeOffTitle': 'Giờ tắt đèn',
    'home.btnUpdate': 'LƯU TẤT CẢ THIẾT LẬP',
    'home.saveSuccess': 'Đã thiết lập thành công',
    'home.saveError': 'Không thể lưu dữ liệu.',
    'profile.title': 'Hồ sơ',
    'profile.edit': 'Chỉnh sửa hồ sơ',
    'profile.settings': 'Cài đặt',
    'profile.help': 'Trợ giúp',
    'profile.about': 'Về ứng dụng',
    'profile.logout': 'Đăng xuất',
    'profile.logoutError': 'Không thể đăng xuất. Vui lòng thử lại.',
    'profile.changePassword': 'Đổi mật khẩu',
    'changePassword.title': 'Đổi mật khẩu',
    'changePassword.description': 'Nhập mật khẩu hiện tại và mật khẩu mới để thay đổi.',
    'changePassword.currentPassword': 'Mật khẩu hiện tại',
    'changePassword.currentPasswordPlaceholder': 'Nhập mật khẩu hiện tại',
    'changePassword.newPassword': 'Mật khẩu mới',
    'changePassword.newPasswordPlaceholder': 'Nhập mật khẩu mới',
    'changePassword.confirmPassword': 'Xác nhận mật khẩu mới',
    'changePassword.confirmPasswordPlaceholder': 'Nhập lại mật khẩu mới',
    'changePassword.button': 'Thay đổi mật khẩu',
    'changePassword.processing': 'Đang xử lý...',
    'changePassword.error': 'Lỗi',
    'changePassword.weakPassword': 'Mật khẩu mới quá yếu',
    'changePassword.recentLoginRequired': 'Vui lòng đăng nhập lại để thực hiện thao tác này',
    'changePassword.success': 'Mật khẩu đã được thay đổi thành công',
    'changePassword.changeError': 'Không thể thay đổi mật khẩu',
    'changePassword.wrongPassword': 'Mật khẩu hiện tại không đúng',
    'changePassword.allFieldsRequired': 'Vui lòng nhập đầy đủ thông tin',
    'changePassword.passwordMismatch': 'Mật khẩu mới và xác nhận mật khẩu không khớp',
    'changePassword.passwordTooShort': 'Mật khẩu mới phải có ít nhất 6 ký tự',
    'changePassword.userNotFound': 'Không tìm thấy thông tin người dùng',
    'graph.title': 'Phân Tích Lưu Lượng',
    'graph.chartTitle': 'Biểu đồ số xe vào/ra (10 giây/lần)',
    'graph.carsIn': 'Số xe vào (hiện tại):',
    'graph.carsOut': 'Số xe ra (hiện tại):',
    'graph.legendIn': 'Số xe vào (10s)',
    'graph.legendOut': 'Số xe ra (10s)',
    'graph.totalLabel': 'Tổng lượt vật cản tích lũy',
    'notifications.title': '🔔 Thông báo',
    'notifications.systemHistory': 'Lịch sử hệ thống',
    'notifications.noNotifications': 'Chưa có thông báo nào',
    'slot.title': 'Hệ thống quản lý bãi đậu',
    'slot.title1': 'Trạng thái bãi giữ xe',
    'slot.empty': 'Trống',
    'slot.occupied': 'Có xe',
    'slot.ready': 'Sẵn Sàng',
    'slot.back': 'Quay lại',
    'slot.slot': 'Vị trí',
    'register.title': 'Đăng ký tài khoản',
    'register.email': 'Email',
    'register.password': 'Mật khẩu',
    'register.submit': 'Đăng ký',
    'register.success': 'Chúc mừng! Bạn đã đăng ký thành công.',
    'register.fail': 'Đăng ký thất bại: ',
    'settings.title': 'Cài đặt',
    'settings.theme': 'Chế độ giao diện',
    'settings.themeDescription': 'Chọn giao diện sáng hoặc tối cho ứng dụng.',
    'settings.light': 'Sáng',
    'settings.dark': 'Tối',
    'settings.language': 'Ngôn ngữ',
    'settings.languageDescription': 'Chọn ngôn ngữ hiển thị cho ứng dụng.',
    'settings.vietnamese': 'Tiếng Việt',
    'settings.english': 'English',
    'settings.note': 'Lưu ý',
    'settings.noteText': 'Thiết lập này áp dụng cho toàn bộ app sau khi bạn chọn.',
    'news.title': 'Tin tức thể thao',
    'news.subtitle': 'Cập nhật các tin thể thao mới nhất từ Google News: bóng đá, bóng rổ, quần vợt, F1 và giải đấu hàng đầu.',
    'news.highlight': 'Nổi bật',
    'news.football': 'Bóng đá',
    'news.basketball': 'Bóng rổ',
    'news.tennis': 'Quần vợt',
    'news.racing': 'Đua xe',
    'news.badminton': 'Cầu lông',
    'news.sports': 'Thể thao',
    'news.olympic': 'Olympic',
    'news.vietnamFootball': 'Tin tức bóng đá Việt Nam',
    'news.basketballHot': 'Bóng rổ HOT',
    'news.tennisTitle': 'Tennis',
    'news.f1Title': 'F1',
    'news.source': 'Báo mới',
    'news.error': 'Không thể kết nối:',
    'news.vietnamFootballdescription': 'Bóng đá Việt Nam - Tin nhanh bóng đá VN mới nhất.',
    'news.basketballHotdescription': 'Cập nhật tin tức giải bóng rổ nhà nghề Mỹ NBA và Việt Nam.',
    'news.tennisTitledescription': 'Tennis 24h - Cập nhật nhanh tin tức Quần vợt mới nhất hôm nay.',
    'news.f1Titledescription': 'Tin tức & video các chặng đua tại cuộc thi đua xe công thức 1 năm nay.',
    'editProfile.title': 'Chỉnh sửa hồ sơ',
    'editProfile.avatarSuccess': 'Ảnh đại diện đã được thay đổi!',
    'editProfile.uploadError': 'Không thể upload ảnh',
    'editProfile.uploadFailed': 'Upload thất bại, thử lại sau',
    'editProfile.nameRequired': 'Tên không được trống',
    'editProfile.updateSuccess': 'Thông tin đã được cập nhật!',
    'editProfile.updateError': 'Không thể cập nhật hồ sơ.',
    'editProfile.uploading': 'Đang tải...',
    'editProfile.changePhoto': 'Thay đổi ảnh đại diện',
    'editProfile.fullName': 'Tên người dùng',
    'editProfile.namePlaceholder': 'Nhập tên của bạn',
    'editProfile.note': 'Lưu ý: Tên này sẽ hiển thị trên thanh điều hướng và trang cá nhân.',
    'editProfile.saveButton': 'Lưu thay đổi',
    'editProfile.saving': 'Đang lưu...',
    'modal.title': 'Đây là modal',
    'modal.goHome': 'Về màn hình chính',
    'door.title': 'Hệ thống cửa bãi xe',
    'door.door1': 'Cửa chỗ xe 1',
    'door.door2': 'Cửa chỗ xe 2',
    'door.door3': 'Cửa chỗ xe 3',
    'door.door4': 'Cửa chỗ xe 4',
    'door.door5': 'Cửa chỗ xe 5',
    'door.door6': 'Cửa chỗ xe 6',
    'door.open': 'Đang mở',
    'door.closed': 'Đang đóng',
    'door.openBtn': 'Mở',
    'door.closeBtn': 'Đóng',
    'door.notConnected': 'Chưa kết nối',
    'door.back': 'Quay lại',
  },
  en: {
    'common.success': 'Success',
    'common.error': 'Error',
    'common.cancel': 'Cancel',
    'nav.overview': 'Overview',
    'nav.graph': 'Statistical',
    'nav.news': 'News',
    'nav.notifications': 'Alerts',
    'nav.profile': 'Profile',
    'home.active': 'Device Control',
    'home.sensors': 'Temperature & Humidity Sensors',
    'home.settings': '⚙️ System Settings',
    'home.title': 'Dashboard',
    'home.overview': 'Overview',
    'home.graph': 'Statistical',
    'home.temp': 'Temperature',
    'home.humi': 'Humidity',
    'home.unitTemp': '°C',
    'home.unitHumi': '%',
    'home.light': 'Light',
    'home.alarm': 'Alarm',
    'home.door': 'Garage Door',
    'home.parking': 'Parking',
    'home.on': 'ON',
    'home.off': 'OFF',
    'home.tempTitle': 'Temperature Threshold',
    'home.timeOnTitle': 'Light On Time',
    'home.timeOffTitle': 'Light Off Time',
    'home.btnUpdate': 'SAVE ALL SETTINGS',
    'home.saveSuccess': 'Settings saved successfully',
    'home.saveError': 'Cannot save data.',
    'home.access': 'Access',
    'home.check': 'Check',
    'home.done': 'Done',
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.settings': 'Settings',
    'profile.help': 'Help',
    'profile.about': 'About app',
    'profile.logout': 'Log out',
    'profile.logoutError': 'Cannot log out. Please try again.',
    'profile.changePassword': 'Change Password',
    'changePassword.title': 'Change Password',
    'changePassword.description': 'Enter your current password and new password to change.',
    'changePassword.currentPassword': 'Current Password',
    'changePassword.currentPasswordPlaceholder': 'Enter current password',
    'changePassword.newPassword': 'New Password',
    'changePassword.newPasswordPlaceholder': 'Enter new password',
    'changePassword.confirmPassword': 'Confirm New Password',
    'changePassword.confirmPasswordPlaceholder': 'Re-enter new password',
    'changePassword.button': 'Change Password',
    'changePassword.processing': 'Processing...',
    'changePassword.error': 'Error',
    'changePassword.weakPassword': 'New password is too weak',
    'changePassword.recentLoginRequired': 'Please log in again to perform this action',
    'changePassword.success': 'Password has been changed successfully',
    'changePassword.changeError': 'Cannot change password',
    'changePassword.wrongPassword': 'Current password is incorrect',
    'changePassword.allFieldsRequired': 'Please fill in all fields',
    'changePassword.passwordMismatch': 'New password and confirm password do not match',
    'changePassword.passwordTooShort': 'New password must be at least 6 characters',
    'changePassword.userNotFound': 'User information not found',
    'graph.title': 'Traffic Analytics',
    'graph.chartTitle': 'Cars In/Out Chart (10s interval)',
    'graph.carsIn': 'Cars In (current):',
    'graph.carsOut': 'Cars Out (current):',
    'graph.legendIn': 'Cars In (10s)',
    'graph.legendOut': 'Cars Out (10s)',
    'graph.totalLabel': 'Total recorded obstacles',
    'notifications.title': '🔔 Notifications',
    'notifications.systemHistory': 'System History',
    'notifications.noNotifications': 'No notifications yet',
    'slot.title': 'Parking Management',
    'slot.title1': 'Parking Status',
    'slot.empty': 'Empty',
    'slot.occupied': 'Occupied',
    'slot.ready': 'Ready',
    'slot.back': 'Back',
    'slot.slot': 'Slot',
    'register.title': 'Create account',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.submit': 'Sign up',
    'register.success': 'Congrats! Your account has been created.',
    'register.fail': 'Register failed: ',
    'settings.title': 'Settings',
    'settings.theme': 'Theme mode',
    'settings.themeDescription': 'Choose light or dark mode for the app.',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Language',
    'settings.languageDescription': 'Choose app language.',
    'settings.vietnamese': 'Tiếng Việt',
    'settings.english': 'English',
    'settings.note': 'Note',
    'settings.noteText': 'These settings apply across the whole app once selected.',
    'news.title': 'Sports News',
    'news.subtitle': 'Latest sports updates from Google News: football, basketball, tennis, F1 and top events.',
    'news.highlight': 'Featured',
    'news.football': 'Football',
    'news.basketball': 'Basketball',
    'news.tennis': 'Tennis',
    'news.racing': 'Racing',
    'news.badminton': 'Badminton',
    'news.sports': 'Sports',
    'news.olympic': 'Olympic',
    'news.vietnamFootball': 'Vietnam Football News',
    'news.basketballHot': 'Basketball HOT',
    'news.tennisTitle': 'Tennis',
    'news.f1Title': 'F1',
    'news.source': 'News Source',
    'news.error': 'Cannot connect:',
    'news.vietnamFootballdescription': 'Vietnamese Football - Latest Vietnamese football news.',
    'news.basketballHotdescription': 'Stay updated on news from the American professional basketball league (NBA) and Vietnam.',
    'news.tennisTitledescription': 'Tennis 24h - Get the latest tennis news updates today.',
    'news.f1Titledescription': "News and videos of this year's Formula 1 races.",
    'editProfile.title': 'Edit Profile',
    'editProfile.avatarSuccess': 'Profile picture has been changed!',
    'editProfile.uploadError': 'Cannot upload image',
    'editProfile.uploadFailed': 'Upload failed, try again later',
    'editProfile.nameRequired': 'Name cannot be empty',
    'editProfile.updateSuccess': 'Profile has been updated!',
    'editProfile.updateError': 'Cannot update profile.',
    'editProfile.uploading': 'Uploading...',
    'editProfile.changePhoto': 'Change Profile Picture',
    'editProfile.fullName': 'User Name',
    'editProfile.namePlaceholder': 'Enter your name',
    'editProfile.note': 'Note: This name will be displayed on navigation bar and profile page.',
    'editProfile.saveButton': 'Save Changes',
    'editProfile.saving': 'Saving...',
    'modal.title': 'This is a modal',
    'modal.goHome': 'Go to home screen',
    'door.title': 'Parking gate system',
    'door.door1': 'Parking Gate 1',
    'door.door2': 'Parking Gate 2',
    'door.door3': 'Parking Gate 3',
    'door.door4': 'Parking Gate 4',
    'door.door5': 'Parking Gate 5',
    'door.door6': 'Parking Gate 6',
    'door.open': 'Opening',
    'door.closed': 'Closing',
    'door.openBtn': 'Open',
    'door.closeBtn': 'Close',
    'door.notConnected': 'Not connected',
    'door.back': 'Back',
  },
};

export const AppSettingsContext = createContext<AppSettingsContextType | undefined>(undefined);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const systemScheme = useRNColorScheme() ?? 'light';
  const [theme, setTheme] = useState<ThemeMode>(systemScheme === 'dark' ? 'dark' : 'light');
  const [language, setLanguageState] = useState<Language>('vi');

  // Load language from Firebase on mount
  useEffect(() => {
    const settingsRef = ref(db, 'thuan/settings/language');
    const unsubscribe = onValue(settingsRef, (snapshot) => {
      const value = snapshot.val();
      if (value && (value === 'vi' || value === 'en')) {
        setLanguageState(value);
      }
    });
    return () => unsubscribe();
  }, []);

  // Wrapper function to save language to Firebase
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    update(ref(db, 'thuan/settings'), { language: lang }).catch(err => 
      console.error('Lỗi lưu ngôn ngữ:', err)
    );
  };

  const t = (key: string) => {
    return translations[language][key] ?? translations.vi[key] ?? key;
  };

  const navigationTheme = useMemo(
    () => (theme === 'dark' ? DarkTheme : DefaultTheme),
    [theme]
  );

  return (
    <AppSettingsContext.Provider value={{ theme, language, setTheme, setLanguage, t }}>
      <ThemeProvider value={navigationTheme}>{children}</ThemeProvider>
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error('useAppSettings must be used within AppSettingsProvider');
  }
  return context;
}
